<?php
return [
  'business' => [
    'title' => 'Business',
    'heading' => 'Create Your Business Profile',
    'subtitle' => 'Build a complete business profile for buyers, investors and partners.',
    'steps' => [
      ['title' => 'Confidential Information', 'description' => 'Add the contact details for your business profile.', 'fields' => [
        ['name' => 'seller_name', 'label' => 'Your Name', 'placeholder' => 'Enter name', 'required' => true],
        ['name' => 'seller_designation', 'label' => 'Designation', 'placeholder' => 'Enter name', 'required' => true],
        ['name' => 'seller_email', 'label' => 'Email', 'type' => 'email', 'placeholder' => 'Enter Email', 'required' => true],
        ['name' => 'seller_mobile', 'label' => 'Mobile No.', 'type' => 'tel', 'placeholder' => 'Enter Mobile', 'required' => true],
      ]],
      ['title' => 'Advertisement Details', 'description' => 'Introduce the opportunity to people viewing your profile.', 'fields' => [
        ['name' => 'advmt_headline', 'label' => 'Advertisement Headline', 'placeholder' => 'Enter Advertisement Headline', 'required' => true, 'wide' => true],
        ['name' => 'seller_intro', 'label' => 'Introduction', 'type' => 'textarea', 'placeholder' => 'Introduce your business', 'wide' => true],
      ]],
      ['title' => 'Business Information', 'description' => 'Describe your company, industry and operations.', 'fields' => [
        ['name' => 'seller_company', 'label' => 'Company Name', 'placeholder' => 'Enter Company', 'required' => true],
        ['name' => 'estb_year', 'label' => 'Establishment Year', 'type' => 'select', 'placeholder' => 'Select Establishment Year', 'options' => range((int) date('Y'), 1900), 'required' => true],
        ['name' => 'emp_count', 'label' => 'Employee Count', 'type' => 'select', 'placeholder' => 'Select Employee Count', 'options' => ['less than 10', '10-50', '50-100', '100-500', '500-1000', 'more than 1000'], 'required' => true],
        ['name' => 'entity_type', 'label' => 'Entity Type', 'type' => 'select', 'placeholder' => 'Select Entity Type', 'options' => ['Proprietorship', 'Partnership', 'Limited Liability Company', 'Private Limited Company', 'Public Limited Company'], 'required' => true],
        ['name' => 'business_type', 'label' => 'Business Type', 'type' => 'select', 'placeholder' => 'Select Business Type', 'options' => ['B2B', 'B2C', 'C2C', 'C2B', 'B2B and B2C'], 'required' => true],
        ['name' => 'industry_sector', 'label' => 'Industry Sector', 'type' => 'select', 'placeholder' => 'Select Industry Sector', 'options' => ['Automobile', 'FMCG', 'Education', 'Beauty, health & wellness', 'Business services', 'Food & beverage', 'Fashion', 'Building construction & Home products', 'Travel & tourism', 'Leisure & Entertainment', 'Finance', 'Energy & Environment', 'Industrial machinery & Manufacturing', 'Retail'], 'required' => true],
        ['name' => 'business_website', 'label' => 'Business Website', 'type' => 'url', 'placeholder' => 'https://example.com'],
        ['name' => 'facilities_desc', 'label' => 'Facilities', 'type' => 'textarea', 'placeholder' => 'Describe your facilities', 'wide' => true],
        ['name' => 'company_summary', 'label' => 'Company Summary', 'type' => 'textarea', 'placeholder' => 'Describe about the Business / Company Summary', 'wide' => true],
      ]],
      ['title' => 'Financial Details', 'description' => 'Share the key financial information for your business.', 'fields' => [
        ['name' => 'annual_sales', 'label' => 'Annual Sales', 'type' => 'number', 'placeholder' => 'Enter Annual Sales'],
        ['name' => 'inventory_value', 'label' => 'Inventory Value', 'type' => 'number', 'placeholder' => 'Enter Inventory Value'],
        ['name' => 'gross_profit', 'label' => 'Gross Income', 'type' => 'number', 'placeholder' => 'Enter Gross Income'],
        ['name' => 'ebitda', 'label' => 'EBITDA', 'type' => 'number', 'placeholder' => 'Enter EBITDA'],
        ['name' => 'ebitda_margin', 'label' => 'EBITDA Margin', 'type' => 'number', 'placeholder' => 'Enter EBITDA Margin'],
        ['name' => 'rentals', 'label' => 'Rentals', 'type' => 'number', 'placeholder' => 'Enter Rentals'],
      ]],
      ['title' => 'Team & Headquarters', 'description' => 'Add your key contacts and business location.', 'fields' => [
        ['name' => 'director_name', 'label' => 'Name', 'placeholder' => 'Enter Your Name'],
        ['name' => 'director_email', 'label' => 'Email id', 'type' => 'email', 'placeholder' => 'Enter Email id'],
        ['name' => 'director_designation', 'label' => 'Designation', 'type' => 'select', 'placeholder' => 'Select Designation', 'options' => ['Director', 'CEO', 'Owner']],
        ['name' => 'contact_name', 'label' => 'Name', 'placeholder' => 'Enter Name'],
        ['name' => 'contact_designation', 'label' => 'Designation', 'placeholder' => 'Enter Designation'],
        ['name' => 'contact_email', 'label' => 'Email', 'type' => 'email', 'placeholder' => 'Enter Email ID'],
        ['name' => 'ofc_address', 'label' => 'Address', 'type' => 'textarea', 'placeholder' => 'Enter Office Address', 'wide' => true],
        ['name' => 'ofc_city', 'label' => 'City', 'placeholder' => 'Enter Your Location'],
        ['name' => 'ofc_country', 'label' => 'Country', 'type' => 'select', 'placeholder' => 'Select Country', 'options' => ['United Kingdom'], 'required' => true],
        ['name' => 'ofc_pincode', 'label' => 'Pin Code', 'placeholder' => 'Enter Pin Code'],
      ]],
      ['title' => 'Requirements & Attachments', 'description' => 'Tell members what you need and add supporting documents.', 'fields' => [
        ['type' => 'checkboxes', 'label' => 'Requirements', 'wide' => true, 'options' => [
          ['name' => 'seeking_investors', 'label' => 'Investors for My business'],
          ['name' => 'seeking_loan', 'label' => 'Loan'],
          ['name' => 'seeking_accelerators', 'label' => 'Accelerators'],
          ['name' => 'seeking_buyers', 'label' => 'Buyers'],
          ['name' => 'seeking_mentors', 'label' => 'Mentors'],
        ]],
        ['name' => 'inv_asking_price', 'label' => 'Amount of investment you are looking for', 'type' => 'number', 'placeholder' => 'Enter Amount'],
        ['name' => 'inv_stake', 'label' => 'Business stake of the investment', 'type' => 'number', 'placeholder' => 'Enter Stake'],
        ['name' => 'inv_reason', 'label' => 'Reason for investment', 'placeholder' => 'Enter Reason for investment'],
        ['name' => 'buyer_sell_price', 'label' => 'Selling (Asking) Price', 'type' => 'number', 'placeholder' => 'Enter Asking Price'],
        ['name' => 'buyer_sell_reason', 'label' => 'Reason for Selling', 'placeholder' => 'Enter Your Reason for selling'],
        ['name' => 'loan_collateral_details', 'label' => 'Collateral details', 'placeholder' => 'Enter details'],
        ['name' => 'loan_amount', 'label' => 'Loan amount seeking', 'type' => 'number', 'placeholder' => 'Enter Amount'],
        ['name' => 'loan_repayment_period', 'label' => 'Possible repayment period', 'type' => 'select', 'placeholder' => 'Select Possible repayment period', 'options' => ['3 Month', '6 Month', '9 Month', '1 Year', '2 Year', 'more than 2 Year']],
        ['name' => 'loan_interest_rate', 'label' => 'Expected Interest Rate', 'type' => 'select', 'placeholder' => 'Select Expected Interest Rate', 'options' => ['0-5', '5-10', '10-25', '25-35', '40-50', 'more than 50']],
        ['name' => 'loan_reason', 'label' => 'Reason for loan', 'placeholder' => 'Enter Reason for loan'],
        ['name' => 'mentor_req_details', 'label' => 'Mentorship Requirement Details', 'type' => 'textarea', 'placeholder' => 'Mentorship Requirement Details', 'wide' => true],
        ['name' => 'mentor_support_field', 'label' => 'Field of Mentorship', 'placeholder' => 'Field of Mentorship'],
        ['name' => 'accel_req_details', 'label' => 'Accelerator requirement details', 'placeholder' => 'Enter your Req'],
        ['name' => 'accel_inv_req', 'label' => 'Investment Requirement', 'type' => 'number', 'placeholder' => 'Enter your Amount'],
        ['name' => 'support_field', 'label' => 'Field of support needed', 'placeholder' => 'Field of support needed'],
        ['name' => 'accel_time_period', 'label' => 'Time period of support needed', 'type' => 'select', 'placeholder' => 'Select Time period of support needed', 'options' => ['3 Month', '6 Month', '9 Month', '1 Year', '2 Year']],
        ['name' => 'business_pitch', 'label' => 'One line pitch for your business', 'type' => 'textarea', 'placeholder' => 'One line pitch for your business', 'wide' => true],
        ['name' => 'business_photo_1', 'label' => 'Business Photo', 'type' => 'file', 'accept' => '.png,.jpg,.jpeg'],
        ['name' => 'business_photo_2', 'label' => 'Business Photo', 'type' => 'file', 'accept' => '.png,.jpg,.jpeg'],
        ['name' => 'business_photo_3', 'label' => 'Business Photo', 'type' => 'file', 'accept' => '.png,.jpg,.jpeg'],
        ['name' => 'business_photo_4', 'label' => 'Business Photo', 'type' => 'file', 'accept' => '.png,.jpg,.jpeg'],
        ['name' => 'business_document_1', 'label' => 'Business Documents', 'type' => 'file', 'accept' => '.doc,.docx,.xls,.xlsx,.pdf'],
        ['name' => 'business_document_2', 'label' => 'Business Documents', 'type' => 'file', 'accept' => '.doc,.docx,.xls,.xlsx,.pdf'],
        ['name' => 'business_document_3', 'label' => 'Business Documents', 'type' => 'file', 'accept' => '.doc,.docx,.xls,.xlsx,.pdf'],
        ['name' => 'business_document_4', 'label' => 'Business Documents', 'type' => 'file', 'accept' => '.doc,.docx,.xls,.xlsx,.pdf'],
      ]],
    ],
  ],
  'investor' => [
    'title' => 'Investor',
    'heading' => 'Create Your Investor Profile',
    'subtitle' => 'Share your investment focus with businesses and founders.',
    'steps' => [
      ['title' => 'Confidential Information', 'description' => 'Add your contact details and location.', 'fields' => [
        ['name' => 'inv_name', 'label' => 'Your Name', 'placeholder' => 'Enter name', 'required' => true],
        ['name' => 'inv_email', 'label' => 'Email', 'type' => 'email', 'placeholder' => 'Enter Email', 'required' => true],
        ['name' => 'inv_mobile', 'label' => 'Mobile No.', 'type' => 'tel', 'placeholder' => 'Enter Mobile Number', 'required' => true],
        ['name' => 'inv_city', 'label' => 'Location', 'placeholder' => 'Enter Your Location', 'required' => true],
      ]],
      ['title' => 'Advertisement Details', 'description' => 'Introduce your investor profile.', 'fields' => [
        ['name' => 'inv_headline', 'label' => 'Advertisement Headline', 'placeholder' => 'Enter Advertisement Headline', 'required' => true, 'wide' => true],
        ['name' => 'inv_intro', 'label' => 'Introduction', 'type' => 'textarea', 'placeholder' => 'Introduce your investment profile', 'wide' => true],
      ]],
      ['title' => 'Investor Profile', 'description' => 'Tell us about your investment background.', 'fields' => [
        ['name' => 'inv_type', 'label' => 'Investor Type', 'type' => 'select', 'placeholder' => 'Select Investor Type', 'options' => ['Individual Investor', 'Investment Firm'], 'required' => true],
        ['name' => 'linkedin_profile', 'label' => 'Your LinkedIn Profile', 'type' => 'url', 'placeholder' => 'Enter URL'],
        ['name' => 'location_pref', 'label' => 'Location Preference', 'placeholder' => 'Enter Location Preference'],
        ['name' => 'sector_preference', 'label' => 'Sector Preference', 'placeholder' => 'Choose sectors'],
        ['name' => 'inv_abt_urself', 'label' => 'About Yourself', 'type' => 'textarea', 'placeholder' => 'Enter About Yourself', 'wide' => true],
      ]],
      ['title' => 'Investment Preferences', 'description' => 'Set your investment range and acquisition preferences.', 'fields' => [
        ['type' => 'checkboxes', 'label' => 'Investment', 'wide' => true, 'options' => [
          ['name' => 'invest_pref_name', 'label' => 'Investment'],
          ['name' => 'full_acquisition', 'label' => 'Full Acquisition'],
        ]],
        ['name' => 'invest_size_min', 'label' => 'Minimum Investment Size', 'placeholder' => 'Enter Min Amount'],
        ['name' => 'invest_size_max', 'label' => 'Maximum Investment Size', 'placeholder' => 'Enter Max Amount'],
        ['name' => 'invest_stake', 'label' => 'Stake', 'placeholder' => 'Enter %'],
        ['name' => 'purchase_capacity_min', 'label' => 'Minimum Purchase Capacity', 'placeholder' => 'Enter Min'],
        ['name' => 'purchase_capacity_max', 'label' => 'Maximum Purchase Capacity', 'placeholder' => 'Enter Max'],
      ]],
      ['title' => 'Company Details', 'description' => 'Add details about your firm or organization.', 'fields' => [
        ['name' => 'company_name', 'label' => 'Company Name', 'placeholder' => 'Enter Company Name'],
        ['name' => 'company_designation', 'label' => 'Designation', 'placeholder' => 'Enter Designation'],
        ['name' => 'firm_type', 'label' => 'Firm Type', 'type' => 'select', 'placeholder' => 'Select Firm Type', 'options' => ['Corporate Investment Firm', 'Private Equity Firm', 'Venture Capital Firm']],
        ['name' => 'company_city', 'label' => 'Company Location', 'placeholder' => 'Enter Location'],
        ['name' => 'company_pincode', 'label' => 'Pin Code', 'placeholder' => 'Enter Pin Code'],
        ['name' => 'company_website', 'label' => 'Company Website', 'type' => 'url', 'placeholder' => 'Enter URL'],
        ['name' => 'company_summary', 'label' => 'Company Summary', 'type' => 'textarea', 'placeholder' => 'Enter Company Summary', 'wide' => true],
      ]],
      ['title' => 'Attachments & Review', 'description' => 'Add a profile image and a supporting document before submitting.', 'fields' => [
        ['name' => 'investor_photo', 'label' => 'Profile Image', 'type' => 'file', 'accept' => '.png,.jpg,.jpeg'],
        ['name' => 'investor_document', 'label' => 'Supporting Document', 'type' => 'file', 'accept' => '.doc,.docx,.xls,.xlsx,.pdf'],
      ]],
    ],
  ],
  'mentor' => [
    'title' => 'Mentor',
    'heading' => 'Create Your Mentor Profile',
    'subtitle' => 'Showcase your experience and help businesses grow.',
    'steps' => [
      ['title' => 'Confidential Information', 'description' => 'Add your contact details and location.', 'fields' => [
        ['name' => 'mentor_name', 'label' => 'Your Name', 'placeholder' => 'Enter your Name', 'required' => true],
        ['name' => 'mentor_email', 'label' => 'Email', 'type' => 'email', 'placeholder' => 'Enter Email', 'required' => true],
        ['name' => 'mentor_mobile', 'label' => 'Mobile No.', 'type' => 'tel', 'placeholder' => 'Enter Mobile', 'required' => true],
        ['name' => 'mentor_location', 'label' => 'Location', 'placeholder' => 'Type Location', 'required' => true],
      ]],
      ['title' => 'Advertisement Details', 'description' => 'Add the headline and introduction shown on your profile.', 'fields' => [
        ['name' => 'mentor_adv_headline', 'label' => 'Advertisement Headline', 'placeholder' => 'Enter Advertisement Headline', 'required' => true, 'wide' => true],
        ['name' => 'mentor_intro', 'label' => 'Introduction', 'type' => 'textarea', 'placeholder' => 'Introduce your mentoring services', 'wide' => true],
      ]],
      ['title' => 'Professional Information', 'description' => 'Add your occupation, company and experience summary.', 'fields' => [
        ['name' => 'mentor_occupation', 'label' => 'Occupation', 'type' => 'select', 'placeholder' => 'Select Occupation', 'options' => ['Corporate Professional', 'Educational Professional'], 'required' => true],
        ['name' => 'mentor_company', 'label' => 'Company', 'placeholder' => 'Enter your Company Name'],
        ['name' => 'mentor_designation', 'label' => 'Designation', 'placeholder' => 'Enter your Designation'],
        ['name' => 'prof_exp_year', 'label' => 'Number Of Years', 'type' => 'select', 'placeholder' => 'Number Of Years', 'options' => range(1, 20)],
        ['name' => 'mentor_profile_summary', 'label' => 'Professional Summary', 'type' => 'textarea', 'placeholder' => 'Describe your professional experience', 'wide' => true],
      ]],
      ['title' => 'Expertise', 'description' => 'Select your industry and subject expertise.', 'fields' => [
        ['name' => 'mentor_sector_expertise', 'label' => 'Sector Expertise', 'type' => 'select', 'placeholder' => 'Select Sector Expertise', 'options' => ['Automobile', 'Business services', 'Education', 'Finance', 'Food & beverage', 'Healthcare', 'Manufacturing', 'Technology']],
        ['name' => 'support_field', 'label' => 'Subject Expertise', 'placeholder' => 'Subject Expertise'],
        ['name' => 'Sector_PreferenceIndi', 'label' => 'Sector Preference', 'placeholder' => 'Sector Preference'],
      ]],
      ['title' => 'Online Profile', 'description' => 'Link to your professional profile.', 'fields' => [
        ['name' => 'mentor_linkedin', 'label' => 'LinkedIn Profile', 'type' => 'url', 'placeholder' => 'Enter URL', 'wide' => true],
      ]],
      ['title' => 'Attachments & Review', 'description' => 'Add a profile image and a supporting document before submitting.', 'fields' => [
        ['name' => 'mentor_profile_image', 'label' => 'Upload Image', 'type' => 'file', 'accept' => '.png,.jpg,.jpeg'],
        ['name' => 'mentor_document', 'label' => 'Supporting Document', 'type' => 'file', 'accept' => '.doc,.docx,.xls,.xlsx,.pdf'],
      ]],
    ],
  ],
  'startup' => [
    'title' => 'Startup',
    'heading' => 'Create Your Start-up Profile',
    'subtitle' => 'Share your startup, product and funding requirements.',
    'steps' => [
      ['title' => 'Confidential Information', 'description' => 'Add the primary contact details for your startup.', 'fields' => [
        ['name' => 'startup_name', 'label' => 'Your Name', 'placeholder' => 'Enter name', 'required' => true],
        ['name' => 'startup_designation', 'label' => 'Designation', 'placeholder' => 'Enter name', 'required' => true],
        ['name' => 'startup_email', 'label' => 'Email', 'type' => 'email', 'placeholder' => 'Enter Email', 'required' => true],
        ['name' => 'startup_mobile', 'label' => 'Mobile No.', 'type' => 'tel', 'placeholder' => 'Enter Mobile', 'required' => true],
      ]],
      ['title' => 'Advertisement Details', 'description' => 'Introduce your startup opportunity.', 'fields' => [
        ['name' => 'advmt_headline', 'label' => 'Advertisement Headline', 'placeholder' => 'Enter Advertisement Headline', 'required' => true, 'wide' => true],
        ['name' => 'startup_intro', 'label' => 'Introduction', 'type' => 'textarea', 'placeholder' => 'Introduce your startup', 'wide' => true],
      ]],
      ['title' => 'Company Information', 'description' => 'Add your entity, industry and operational details.', 'fields' => [
        ['name' => 'name_of_entity', 'label' => 'Name of Entity', 'placeholder' => 'Please enter name of entity', 'required' => true],
        ['name' => 'business_type', 'label' => 'Business Type', 'type' => 'select', 'placeholder' => 'Select Business Type', 'options' => ['B2B', 'B2C', 'C2C', 'C2B', 'B2B and B2C']],
        ['name' => 'nature_of_entity', 'label' => 'Nature Of Entity', 'type' => 'select', 'placeholder' => 'Select Nature Of Entity', 'options' => ['Proprietorship', 'Partnership', 'Limited Liability Company', 'Private Limited Company', 'Public Limited Company']],
        ['name' => 'industry_sector', 'label' => 'Industry Sector', 'type' => 'select', 'placeholder' => 'Select Industry Sector', 'options' => ['Automobile', 'FMCG', 'Education', 'Beauty, health & wellness', 'Business services', 'Food & beverage', 'Fashion', 'Building construction & Home products', 'Finance', 'Manufacturing', 'Technology']],
        ['name' => 'estb_date', 'label' => 'Establishment Year', 'type' => 'select', 'placeholder' => 'Select Establishment Year', 'options' => range(2021, 1900)],
        ['name' => 'emp_count', 'label' => 'Number Of Employees', 'type' => 'select', 'placeholder' => 'Select Number Of Employees', 'options' => ['less than 10', '10-50', '50-100', '100-500', '500-1000', 'more than 1000']],
        ['name' => 'incorporation_certificate', 'label' => 'Certification of incorporation', 'type' => 'file', 'accept' => '.doc,.docx,.xls,.xlsx,.pdf'],
        ['name' => 'business_website', 'label' => 'Website', 'type' => 'url', 'placeholder' => 'Enter Website'],
        ['name' => 'facilities_desc', 'label' => 'Facilities', 'type' => 'textarea', 'placeholder' => 'Describe your facilities'],
        ['name' => 'company_summary', 'label' => 'Company Summary', 'type' => 'textarea', 'placeholder' => 'Company Summary', 'wide' => true],
      ]],
      ['title' => 'Financial & Funding Details', 'description' => 'Describe your current funding stage and financial position.', 'fields' => [
        ['name' => 'company_stage', 'label' => 'Select your Company stage', 'type' => 'select', 'placeholder' => 'Select your Company stage', 'options' => ['Not Set', 'Concept Stage', 'Development phase', 'Prototype ready', 'Full business established']],
        ['name' => 'fund_stage', 'label' => 'Round of funding', 'type' => 'select', 'placeholder' => 'Round of funding', 'options' => ['Seed Funding', 'Series A', 'Series B', 'Series C']],
        ['name' => 'fund_amount', 'label' => 'Investment amount', 'placeholder' => 'Enter Investment amount'],
        ['name' => 'annual_sales', 'label' => 'Annual Sales', 'placeholder' => 'Enter Annual Sales'],
        ['name' => 'inventory_value', 'label' => 'Inventory Value', 'placeholder' => 'Enter Inventory Value'],
        ['name' => 'gross_profit', 'label' => 'Gross Income', 'placeholder' => 'Enter Gross Income'],
        ['name' => 'ebitda', 'label' => 'EBITDA', 'placeholder' => 'Enter EBITDA'],
        ['name' => 'ebitda_margin', 'label' => 'EBITDA Margin', 'placeholder' => 'Enter EBITDA Margin'],
        ['name' => 'rentals', 'label' => 'Rentals', 'placeholder' => 'Enter Rentals'],
      ]],
      ['title' => 'Product, Market & Team', 'description' => 'Explain the problem, solution, market and people behind your startup.', 'fields' => [
        ['name' => 'customer_problem', 'label' => 'Customer Problem & Solution', 'type' => 'textarea', 'placeholder' => 'Describe the customer problem and your solution', 'wide' => true],
        ['name' => 'product_service', 'label' => "Start-up's Product / Service", 'type' => 'textarea', 'placeholder' => 'Describe your product or service', 'wide' => true],
        ['name' => 'target_customer', 'label' => 'Target Customer Segment', 'type' => 'textarea', 'placeholder' => 'Describe your target customer', 'wide' => true],
        ['name' => 'target_market', 'label' => 'Target Market', 'type' => 'textarea', 'placeholder' => 'Describe your target market', 'wide' => true],
        ['name' => 'competitors', 'label' => 'Competitors', 'placeholder' => 'List your competitors'],
        ['name' => 'competitive_advantage', 'label' => 'Competitive Advantage', 'placeholder' => 'Describe your advantage'],
        ['name' => 'sales_marketing', 'label' => 'Sales & Marketing strategy', 'placeholder' => 'Describe your strategy'],
        ['name' => 'director_name', 'label' => 'Name', 'placeholder' => 'Enter Your Name'],
        ['name' => 'director_email', 'label' => 'Email id', 'type' => 'email', 'placeholder' => 'Enter Email id'],
        ['name' => 'director_designation', 'label' => 'Designation', 'type' => 'select', 'placeholder' => 'Select Designation', 'options' => ['Director', 'CEO', 'Owner']],
        ['name' => 'facebook_profile', 'label' => 'Facebook', 'placeholder' => 'Enter Facebook profile'],
        ['name' => 'twitter_profile', 'label' => 'Twitter', 'placeholder' => 'Enter Twitter profile'],
        ['name' => 'linkedin_profile', 'label' => 'Linkedin', 'type' => 'url', 'placeholder' => 'Enter LinkedIn profile'],
        ['name' => 'ofc_address', 'label' => 'Address', 'type' => 'textarea', 'placeholder' => 'Enter Office Address', 'wide' => true],
        ['name' => 'ofc_city', 'label' => 'City', 'placeholder' => 'Enter Your Location'],
        ['name' => 'ofc_pincode', 'label' => 'Pin Code', 'placeholder' => 'Enter Pin Code'],
        ['name' => 'contact_name', 'label' => 'Name', 'placeholder' => 'Enter Name'],
        ['name' => 'contact_designation', 'label' => 'Designation', 'placeholder' => 'Enter Designation'],
        ['name' => 'contact_email', 'label' => 'Email', 'type' => 'email', 'placeholder' => 'Enter Email ID'],
      ]],
      ['title' => 'Requirements & Attachments', 'description' => 'Choose the support you need and attach profile materials.', 'fields' => [
        ['type' => 'checkboxes', 'label' => 'Requirements', 'wide' => true, 'options' => [
          ['name' => 'seeking_investors', 'label' => 'Investors'],
          ['name' => 'seeking_loan', 'label' => 'Loan'],
          ['name' => 'seeking_incubators', 'label' => 'Incubators'],
          ['name' => 'seeking_acquirers', 'label' => 'Acquirers'],
          ['name' => 'seeking_mentorship', 'label' => 'Mentorship'],
        ]],
        ['name' => 'inv_asking_price', 'label' => 'Amount of investment you are looking for', 'placeholder' => 'Enter Amount'],
        ['name' => 'inv_stake', 'label' => 'Business stake of the investment', 'placeholder' => 'Enter Stake'],
        ['name' => 'inv_reason', 'label' => 'Reason for investment', 'placeholder' => 'Enter Reason for investment'],
        ['name' => 'buyer_sell_price', 'label' => 'Selling (Asking) Price', 'placeholder' => 'Enter Asking Price'],
        ['name' => 'buyer_sell_reason', 'label' => 'Reason for Selling', 'placeholder' => 'Enter Your Reason for selling'],
        ['name' => 'loan_collateral_details', 'label' => 'Collateral details', 'placeholder' => 'Enter details'],
        ['name' => 'loan_amount', 'label' => 'Loan amount seeking', 'placeholder' => 'Enter Amount'],
        ['name' => 'loan_repayment_period', 'label' => 'Possible repayment period', 'type' => 'select', 'placeholder' => 'Select Possible repayment period', 'options' => ['3 Month', '6 Month', '9 Month', '1 Year', '2 Year', 'more than 2 Year']],
        ['name' => 'loan_interest_rate', 'label' => 'Expected Interest Rate', 'type' => 'select', 'placeholder' => 'Select Expected Interest Rate', 'options' => ['0-5', '5-10', '10-25', '25-35', '40-50', 'more than 50']],
        ['name' => 'loan_reason', 'label' => 'Reason for loan', 'placeholder' => 'Enter Reason for loan'],
        ['name' => 'mentor_req_details', 'label' => 'Mentorship Requirement Details', 'type' => 'textarea', 'placeholder' => 'Mentorship Requirement Details', 'wide' => true],
        ['name' => 'support_fieldMentor', 'label' => 'Field of Mentorship', 'placeholder' => 'Field of Mentorship'],
        ['name' => 'accel_req_details', 'label' => 'Accelerator requirement details', 'placeholder' => 'Enter your Req'],
        ['name' => 'accel_inv_req', 'label' => 'Investment Requirement', 'placeholder' => 'Enter your Amount'],
        ['name' => 'support_field', 'label' => 'Field of support needed', 'placeholder' => 'Field of support needed'],
        ['name' => 'accel_time_period', 'label' => 'Time period of support needed', 'type' => 'select', 'placeholder' => 'Select Time period of support needed', 'options' => ['3 Month', '6 Month', '9 Month', '1 Year', '2 Year']],
        ['name' => 'business_pitch', 'label' => 'One line pitch for your business', 'type' => 'textarea', 'placeholder' => 'One line pitch for your business', 'wide' => true],
        ['name' => 'startup_photo_1', 'label' => 'Business Photo', 'type' => 'file', 'accept' => '.png,.jpg,.jpeg'],
        ['name' => 'startup_photo_2', 'label' => 'Business Photo', 'type' => 'file', 'accept' => '.png,.jpg,.jpeg'],
        ['name' => 'startup_photo_3', 'label' => 'Business Photo', 'type' => 'file', 'accept' => '.png,.jpg,.jpeg'],
        ['name' => 'startup_photo_4', 'label' => 'Business Photo', 'type' => 'file', 'accept' => '.png,.jpg,.jpeg'],
        ['name' => 'startup_document_1', 'label' => 'Business Documents', 'type' => 'file', 'accept' => '.doc,.docx,.xls,.xlsx,.pdf'],
        ['name' => 'startup_document_2', 'label' => 'Business Documents', 'type' => 'file', 'accept' => '.doc,.docx,.xls,.xlsx,.pdf'],
        ['name' => 'startup_document_3', 'label' => 'Business Documents', 'type' => 'file', 'accept' => '.doc,.docx,.xls,.xlsx,.pdf'],
      ]],
    ],
  ],
];
